### ISSUE TITLE
Unable to start ADBView

### ISSUE THREAD

**Issue by withoutclass** [quarnster/ADBView#20]
When I attempt to start ADBView, nothing happens.  I have the following log from console.

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./adbview.py", line 441, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/telnetlib.py", line 319, in read_until
    return self.read_very_lazy()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/telnetlib.py", line 395, in read_very_lazy
    raise EOFError, 'telnet connection closed'
EOFError: telnet connection closed
```

Running OSX 10.8.2

**Comment by dean-clancy-accedo-tv** [comment]
When trying to Start (ctrl + alt + d) ADBView I get a dialog with the following message :

Error trying to launch ADB:

[u'adb', 'devices']

Traceback (most recent call last):
  File "./adbview.py", line 497, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory


I have tried a reboot but no Joy.

**Comment by favasconcelos** [comment]
Same error here, adb is already on the system path.

```
Error trying to launch ADB:

['adb', 'devices']

Traceback (most recent call last):
  File "adbview in /home/user/.config/sublime-text-3/Installed Packages/ADBView.sublime-package", line 497, in run
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'adb'
```

**Comment by zjx20** [comment]
There are two ways to get rid of this error:
* by specifying the absolute path of `adb` (take a look at #11  for more details)
* by installing another SublimeText package `Fix Mac Path` to fix the `PATH` environment variable (from #27)

**Comment by favasconcelos** [comment]
> There are two ways to get rid of this error:
by specifying the absolute path of adb (take a look at #11 for more details)
by installing another SublimeText package Fix Mac Path to fix the PATH environment variable (from #27)
> **zjx20**

I managed to fix it by setting the full adb path, thanks.

**Comment by Springwu1** [comment]
Error trying to launch ADB:

['adb', 'devices']

Traceback (most recent call last):
  File "adbview in /Users/wujiangming/Library/Application Support/Sublime Text 3/Installed Packages/ADBView.sublime-package", line 519, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'adb'

**Comment by dskinner** [comment]
@Springwu1 you need to set the path to the `adb` executable which will be located in where ever you have the android sdk installed on your machine, e.g. `/Users/wujiangming/android-sdk/platform-tools/adb`
