### ISSUE TITLE
ADBView can not start adb cmd despite part of path

### ISSUE THREAD

**Issue by JoachimR** [quarnster/ADBView#28]
Despite being able to start adb from linux command line (because I have added android-sdk-linux/platform-tools to my $PATH) I can not start your plugin from within sublime:

~~~
Error trying to launch ADB:

['adb', 'devices']

Traceback (most recent call last):
  File "adbview in /u/joachim/.config/sublime-text-3/Installed Packages/ADBView.sublime-package", line 415, in run
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'adb'
~~~

what am I doing wrong ?

**Comment by quarnster** [comment]
Try setting the "adb_command" setting to the full path of your adb.
